### ISSUE TITLE
Add support for @Mentions

### ISSUE THREAD

**Issue by glassp** [Becklyn/deploy-message-generator#2]
It would be nice if arbitrary names could be passed after the required args.
These names could be looked up in the ChatSystem and could be transformed into `@mentions` given the ChatSystem supports that.

Then Chat messages could then use the format `@User1 @User2 ... @UserN 'xyz' was deployed to 'abc'`

**Comment by keichinger** [comment]
Added in [v2.1.0](https://github.com/Becklyn/deploy-message-generator/releases/tag/2.1.0)
